### PR TITLE
Rscope navigation tool

### PR DESCRIPTION
**Pull request by schouleu**
This is a tool to display, browse and modify the rscope-marker-ring which contains the stack of markers keeping track of your jumps using rscope

### CODE REVIEW

**Comment by rjarzmik** [comment]
schouleu <notifications@github.com> writes:

So for the patches :
 - please review the trailing whitespaces and anihilate them
 - for patch 2 (Stop searching rscope buffers by prefix), I don't like it
   because the buffer list will be endlessly growing, and will never shrink.
   Therefore, I'd like to drop this patch, and either :
     - rename *rscope-nav* to *rscope_nav"
     - or rename the current *rscope-... to *rscope_...
     - ore something else in this style
 - for patch 1
>+    (define-key map (kbd "RET") 'rscope-nav-open-entry)
   I'd like to have the (kbd "<S-return>") to open in the current window,
   exactly as in rscope rscope-select-entry-current-window
   And (kbd <SPC>) for preview.

>+;;   Do some rscope tag researchs without popping them
                          Typo, "research" or "lookups"

>+  "Refresh *rscop-nav* buffer"
              Typo here.

 - README.org
   The list of keys should be prefixed with a simple space to keep consistency.

Otherwise I have no comment about code, it looks good to me.

Cheers.

--
Robert

**Comment by schouleu** [comment]
The buffer list will only keep track of living rscope database buffers,
wich is quiet limited in an emacs session life I think.
Look at the rscope-get-cscope-buffers() which deletes buffers from the list
which are not living buffers anymore.

I'm ok with the other change requests


2015-04-07 21:25 GMT+02:00 Jarzmik <notifications@github.com>:

**Comment by schouleu** [comment]
Good to go for this one

**Comment by rjarzmik** [comment]
schouleu <notifications@github.com> writes:

> Good to go for this one
Pulled, thanks !

-- 
Robert

**Pull request closed without merging**
